FROM docker/whalesay:latest
#RUN apt-get -y update && apt-get install -y fortunes-ru
#RUN apt-get install -y language-pack-ru
#ENV LANGUAGE ru_RU.UTF-8
#ENV LANG ru_RU.UTF-8
#ENV LC_ALL ru_RU.UTF-8
#RUN locale-gen ru_RU.UTF-8 && dpkg-reconfigure locales
CMD /usr/games/fortune  | cowsay

